name: Flask App CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/EC2_key
          chmod 600 ~/.ssh/EC2_key
          echo "ssh key added!"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo "ec2 key added to trusted ssh hosts"
    
      - name: repo check
        run: |
          ssh -i ~/.ssh/EC2_key ec2-user@${{secrets.EC2_HOST}} << 'EOF'
          if [ ! -d /home/ec2-user/simple-flask-smorest-rest-api ]; then
            git clone https://github.com/MosElAgab/simple-flask-smorest-rest-api.git /home/ec2-user/simple-flask-smorest-rest-api
          else
            echo repo exists
          fi
          EOF

      - name: Upload .env
        run: |
          ssh -i ~/.ssh/EC2_key ec2-user@${{secrets.EC2_HOST}} << 'EOF'
          echo '${{secrets.DOTENV_SECRETS}}' > /home/ec2-user/simple-flask-smorest-rest-api/.env
          EOF

      - name: deploy code to EC2
        run: |
          ssh -i ~/.ssh/EC2_key ec2-user@${{secrets.EC2_HOST}} << 'EOF'
          cd /home/ec2-user/simple-flask-smorest-rest-api
          git pull origin main
          sudo make up
          sudo make migrate
          EOF
