name: Flask App CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/EC2_key
          chmod 600 ~/.ssh/EC2_key
          echo "ssh key added!"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo "ec2 key added to trusted ssh hosts"
      
      - name: deploy code to EC2
        run: |
          ssh -i ~/.ssh/EC2_KEY ec2-user@${{secrets.EC2_HOST}} << 'EOF'
          pwd
          EOF
